#!/usr/bin/env bash

set -e
set -o pipefail

cd "$(dirname $0)"/..

box() {
    local text="$@"
    local hr=$(printf '+-%*s-+' "${#text}" | tr ' ' '-')
    echo "$hr"
    echo "| $text |"
    echo "$hr"
}

box "Building logic layer"
pushd src/logic
wasm-pack build frontend
popd

box "Building frontend site"
pushd src/frontend
yarn
yarn build
popd

box "Done!"
