#!/usr/bin/env bash

set -e
set -o pipefail

cd "$(dirname $0)"/..

box() {
    local text="$@"
    local hr=$(printf '+-%*s-+' "${#text}" | tr ' ' '-')
    echo "$hr"
    echo "| $text |"
    echo "$hr"
}

box "Building logic layer"
pushd logic/entrypoints/frontend
wasm-pack build
popd

box "Building frontend site"
pushd backend/src
yarn
yarn build
popd

box "Done!"
